### ISSUE TITLE
Error saat php artisan migrate --seed

### ISSUE THREAD

**Issue by fahreza007** [gemul/inventory-laravel#1]
Illuminate\Database\QueryException  : SQLSTATE[42S01]: Base table or view alr eady exists: 1050 Table 'user' already exists (SQL: create table `user` (`iduser ` int unsigned not null auto_increment primary key, `nama` varchar(191) null, `u sername` varchar(45) null, `password` varchar(64) null, `remember_token` varchar (100) null, `hak` text null comment 'json hak', `aktif` tinyint(1) null default  '1', `deleted` tinyint(1) null default '0', `created` datetime null default CURR ENT_TIMESTAMP, `updated` datetime null default NULL ON UPDATE CURRENT_TIMESTAMP,  `is_admin` tinyint null default '0') default character set utf8 collate 'utf8_u nicode_ci' engine = InnoDB)                                                                                                                                         at E:\xampp\htdocs\inventory-laravel\vendor\laravel\framework\src\Illuminate\D atabase\Connection.php:664                                                           660\|         // If an exception occurs when attempting to run a query, we'll  format the error                                                                    661\|         // message to include the bindings with SQL, which will make th is exception a                                                                       662\|         // lot more helpful to the developer instead of just the databa se's errors.                                                                         663\|         catch (Exception $e) {                                            > 664\|             throw new QueryException(                                       665\|                 $query, $this->prepareBindings($bindings), $e               666\|             );                                                              667\|         }                                                                   668\|                                                                                                                                                            Exception trace:                                                                                                                                                  1   PDOException::("SQLSTATE[42S01]: Base table or view already exists: 1050 T able 'user' already exists")                                                           E:\xampp\htdocs\inventory-laravel\vendor\laravel\framework\src\Illuminate\ Database\Connection.php:458                                                                                                                                         2   PDOStatement::execute()                                                          E:\xampp\htdocs\inventory-laravel\vendor\laravel\framework\src\Illuminate\ Database\Connection.php:458                                                                                                                                         Please use the argument -v to see more details.
--

Selamat Sore, saya mengalami error saat memasukan php artisan migrate --seed, Mungkin karna table user ada 2, apakah kalau saya ubah salah satu table akan berpengaruh atau tidak ya? Atau ada cara lain untuk mengatasinya?

Terima Kasih

**Comment by gemul** [comment]
Untuk migrasi dan seeder nya memang masih belum selesai dikerjakan. Database nya dibuat manual dari mysql workbench.

**Comment by fahreza007** [comment]
Jadi saya harus gmana pak? Tolong pencerahanya
Terima kasih

**Comment by gemul** [comment]
Maaf lama responnya. sudah saya tambahkan migration nya di 7c13c38368873ef168a6135bfbdd0ff45c827e09 silahkan coba lakukan 

```
php artisan migrate:fresh
php artisan db:seed
```

Jika muncul pesan class ... not found, jalankan ```composer dump-autoload``` terlebih dahulu
