### ISSUE TITLE
php artisan migrate

### ISSUE THREAD

**Issue by geek-sajjad** [gemul/inventory-laravel#2]
`   Illuminate\Database\QueryException  : SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'user' already exists (SQL: create table `user` (`iduser` int unsigned not null auto_increment primary key, `nama` varchar(191) null, `username` varchar(45) null, `password` varchar(64) null, `remember_token` varchar(100) null, `hak` text null comment 'json hak', `aktif` tinyint(1) null default '1', `deleted` tinyint(1) null default '0', `created` datetime null default CURRENT_TIMESTAMP, `updated` datetime null default NULL ON UPDATE CURRENT_TIMESTAMP, `is_admin` tinyint null default '0') default character set utf8mb4 collate 'utf8mb4_unicode_ci' engine = InnoDB)
`

what is problem ?

**Comment by gemul** [comment]
i forgot to fix the migrations. i've added the migration in 7c13c38368873ef168a6135bfbdd0ff45c827e09. you can try 

```
php artisan migrate:fresh
php artisan db:seed
```

if there's an error saying: class ... not found, try running `composer dump-autoload` first
